apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-api
spec:
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_MESSAGE
              value: "TiffinBox Menu - DEV"
            - name: PODINFO_UI_COLOR
              value: "#2980b9"
