apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: menu-api
    count: 3
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.9.0
patches:
  - path: deployment-patch.yaml
  - target: { kind: Ingress, name: menu-api }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: menu.localhost
